language: python
sudo: false
python:
  - "2.7"
addons:
  apt:
    packages:
      - enchant
before_install:
  - pip install --upgrade setuptools pip wheel
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
